## MYSQLユーザーの作成
## 削除
DELETE FROM MYSQL.USER WHERE USER='tweetappuser';

## 作成
CREATE USER 'tweetappuser'@'localhost' IDENTIFIED BY 'pass';

## 権限付与
GRANT ALL ON TWEET_APP_DB.* TO 'tweetappuser'@'localhost'; 

## 反映
FLUSH PRIVILEGES;

##TOURDBデーターベースの作成
DROP DATABASE IF EXISTS TWEET_APP_DB;
CREATE DATABASE TWEET_APP_DB;
USE TWEET_APP_DB;


##①TWEET テーブル
CREATE TABLE TWEET (
  NAME  VARCHAR(50) NOT NULL,
  TWEET VARCHAR(250),
  DATE  DATETIME
);

##②USERS テーブル
CREATE TABLE USERS (
  USERID   CHAR(20) PRIMARY KEY NOT NULL,
  PASSWORD CHAR(20) NOT NULL
);

##③USER_ROLES テーブル
CREATE TABLE USER_ROLES (
  USERID  CHAR(20) NOT NULL,
  ROLE    CHAR(20) NOT NULL,
  PRIMARY KEY (USERID, ROLE)
);
