## MYSQLユーザーの作成
## 削除
DROP USER IF EXISTS 'tweetuser'@'%';

## 作成
CREATE USER 'tweetuser'@'%' IDENTIFIED BY 'pass';

## 権限付与
GRANT ALL ON TWEET_DB.* to 'tweetuser'@'%' with grant option;

## 反映
FLUSH PRIVILEGES;

##TOURDBデーターベースの作成
DROP DATABASE IF EXISTS TWEET_DB;
CREATE DATABASE TWEET_DB;
USE TWEET_DB;

##①USERS テーブル
CREATE TABLE USERS (
  USERID CHAR(20) PRIMARY KEY NOT NULL,
  NAME VARCHAR(100),
  PASSWORD VARCHAR(500) NOT NULL,
  ROLE CHAR(20) NOT NULL
);

##②TWEET テーブル
CREATE TABLE TWEET (
  TWEETID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERID CHAR(20) NOT NULL,
  TWEET VARCHAR(250),
  DATE  DATETIME,
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

set character_set_client=utf8;
set character_set_connection=utf8;


##①USERS テーブル
INSERT INTO USERS VALUES ('u0001','あきら', 'pass','USER');
INSERT INTO USERS VALUES ('a0001','たかし', 'pass','ADMIN');

##②DESTINATIONテーブル　データ追加
INSERT INTO TWEET (USERID,TWEET,DATE) VALUES('u0001','これが３度目のつぶやきです。','2020/12/06 23:01:34');
INSERT INTO TWEET (USERID,TWEET,DATE) VALUES('u0001','これが２度目のつぶやきです。','2020/12/06 23:01:33');
INSERT INTO TWEET (USERID,TWEET,DATE) VALUES('a0001','これが１度目のつぶやきです。','2020/12/06 23:01:32');
INSERT INTO TWEET (USERID,TWEET,DATE) VALUES('u0001','総理大臣になりました。いえい。','2020/12/06 23:01:31');
INSERT INTO TWEET (USERID,TWEET,DATE) VALUES('a0001','総理大臣になりました。','2020/12/06 23:01:30');

COMMIT;
