## MYSQLユーザーの作成
## 削除
DELETE FROM MYSQL.USER WHERE USER='tweetappuser';

## 作成
CREATE USER 'tweetappuser'@'localhost' IDENTIFIED BY 'pass';

## 権限付与
GRANT ALL ON TWEET_APP_DB.* TO 'tweetappuser'@'localhost'; 

## 反映
FLUSH PRIVILEGES;

##TOURDBデーターベースの作成
DROP DATABASE IF EXISTS TWEET_APP_DB;
CREATE DATABASE TWEET_APP_DB;
USE TWEET_APP_DB;


##①TWEET テーブル
CREATE TABLE TWEET (
  NAME  VARCHAR(50) NOT NULL,
  TWEET VARCHAR(250),
  DATE  DATETIME
);

##②USERS テーブル
CREATE TABLE USERS (
  USERID   CHAR(20) PRIMARY KEY NOT NULL,
  PASSWORD CHAR(20) NOT NULL
);

##③USER_ROLES テーブル
CREATE TABLE USER_ROLES (
  USERID  CHAR(20) NOT NULL,
  ROLE    CHAR(20) NOT NULL,
  PRIMARY KEY (USERID, ROLE)
);


set character_set_client=utf8;
set character_set_connection=utf8;

##①DESTINATIONテーブル　データ追加 例INSERT INTO TWEET VALUES('名前','分',NOW());
INSERT INTO TWEET VALUES('深瀬大地','これが３度目のつぶやきです。','2020/12/06 23:01:34');
INSERT INTO TWEET VALUES('深瀬大地','これが２度目のつぶやきです。','2020/12/06 23:01:33');
INSERT INTO TWEET VALUES('深瀬大地','これが１度目のつぶやきです。','2020/12/06 23:01:32');
INSERT INTO TWEET VALUES('安倍晋三','総理大臣になりました。いえい。','2020/12/06 23:01:31');
INSERT INTO TWEET VALUES('安倍晋三','総理大臣になりました。','2020/12/06 23:01:30');

##②USERS テーブル
INSERT INTO USERS VALUES ('u0001', 'pass');
INSERT INTO USERS VALUES ('a0001', 'pass');

##③USER_ROLES テーブル
INSERT INTO USER_ROLES VALUES ('u0001', 'users');
INSERT INTO USER_ROLES VALUES ('a0001', 'admins');

COMMIT;
