CREATE TABLE USERS (
  USERID CHAR(20) PRIMARY KEY NOT NULL,
  NAME VARCHAR(100),
  PASSWORD VARCHAR(500) NOT NULL,
  ROLE CHAR(20) NOT NULL
);

CREATE TABLE TWEET (
  TWEETID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERID CHAR(20) NOT NULL,
  TWEET VARCHAR(250),
  DATE  DATETIME,
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);